server:
  port : 9092

h2-server:
  port: 8082

spring:
#  h2:
#    console:
#    enabled: true
#    path: /h2-console
#    console.settings.trace: false
#    console.settings.web-allow-others: false

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect